### ISSUE TITLE
Cleanup TODO

### ISSUE THREAD

**Issue by ghost** [antopilo/robinthegame#3]
- These two files ([first](https://github.com/antopilo/robinthegame/blob/5b3416cc4042903b35344cc9d280c0e9ae139d18/worlds/FallingPlatform1.gd) and [second](https://github.com/antopilo/robinthegame/blob/5b3416cc4042903b35344cc9d280c0e9ae139d18/Scripts/FallingPlatform.gd)) are almost identical, delete one and find some generic way to merge the two.
- Change all CamelCase to snake_case.
- Delete all the unused files.
- Rename all the files to not have any random `1` or `2` at the end of it.
- Remove `o`/`i`/`node` naming prefixes for variables or files. [Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation) is total garbage and should be avoided.
- [Load images as images and not resources?](https://github.com/godotengine/godot/issues/18638#issuecomment-386843481) That's what causes [this warning](https://i.imgur.com/v61z4M5.png).
- No hard-coded magic numbers. Nearly all files have some black magic random numbers. Put them in constants.
- Split massive one-line calculations into multiple lines. Scrolling horizontally shouldn't be necessary.
- Avoid [INSANE](https://github.com/antopilo/robinthegame/blob/5b3416cc4042903b35344cc9d280c0e9ae139d18/Scripts/level1.gd#L118) repetition by using functions.
- Better organization of files, they are all over the place.

**Comment by antopilo** [comment]
Yes, a lot of cleanup to do I agree, but can you show me what you mean by "Black magic random numbers".

**Comment by ghost** [comment]
Like this: https://github.com/antopilo/robinthegame/blob/master/Scripts/level1.gd#L52

Any numbers that are directly used in the code that aren't self-explanatory should either be in constants or in some config file. There is also some random `* 0.5`, or `- 8`, or similar things all over the code, easier to follow if they are named variables.
